### ISSUE TITLE
Libvirt domain name

### ISSUE THREAD

**Issue by jellonek** [Mirantis/virtlet#149]
Now we have this name equal to image name (gathered from url).
This is why we can not start several vm instances even having snapshots.
This name should be instead `podId`.

**Comment by ivan4th** [comment]
Maybe using combination of image name & pod id (e.g. `name-containerId`) would be more handy for debugging purposes? Because after this patch inspecting the list of domains in libvirt tells nothing without also looking into virtlet/k8s state. Also, in case if `name-containerId` combination is used will work w/o changes.

**Comment by jellonek** [comment]
I'll look if there is no limit in name length on libvirt side and if there is none - will use `name-containerId` convention.
Good point.

**Comment by jellonek** [comment]
I used a bit other convention - `containerId-name` - so prefix will always have same length and image name will be seen always starting from same column (so it can be simpler to remove using sed/awk if someone will hava a need for this).
