### ISSUE TITLE
Support for Calico

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#224]
As of now, Calico doesn't work with Virtlet because the routes can't be passed  via DHCP.
For this particular case we need to use an SNAT/DNAT-based approach inspired by
https://github.com/att-comdev/dockerfiles/tree/master/kvm-manager

**Comment by maugustosilva** [comment]
@ivan4th Can you please expand on this? In your current DHCP code, you do enable `option 121` ( Classless Static Route Option) to pass routes on `flannel` (I should note that, at least according to Wireshark's decoder, this option 121 is actually malformed). Could you elaborate on what else is needed?

**Comment by jellonek** [comment]
I have to look deeper why it's malformed...

For now calico cni plugin does very unusual network setup (it assigns ip to an interface with afair /32 mask, adds static route to custom router through this interface, and then - tries to setup default route to this router). This configuration can not be easily passed by dhcp, because dhcp clients tries to set up default route before static routes and this leads to failure with such config.

Btw. thx for info about malformed option, looks like I overlooked it...
