### ISSUE TITLE
Run VMs in a single separate container

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#380]
Implement VM isolation as per https://github.com/Mirantis/virtlet/blob/master/docs/design-proposals/vm-isolation.md#using-a-single-separate-container-for-vms

**Comment by warmchang** [comment]
Hi @ivan4th , what is the diffrence between the VMs created by virtlet and virsh tool, it can be managed by virsh or not?
And the VM created by virtlet is a really VM or a logical VM (VM in container just like the DinD)?

**Comment by pigmej** [comment]
@warmchang it's true VM. You can manage it using virsh, but virsh is in separate container therefore we have https://github.com/Mirantis/virtlet/blob/master/examples/virsh.sh you just need to remember that our VMs are managed by k8s therefore all lifecycle operations should go through k8s. You shouldn't also change vm definition in virsh because it will be lost when pod will be recreated.

**Comment by warmchang** [comment]
@pigmej , I got it, thank you for your reply.

**Comment by ivan4th** [comment]
Closed by #398
