### ISSUE TITLE
libvirt container failed to start if no default pool created

### ISSUE THREAD

**Issue by YevhenD** [Mirantis/virtlet#51]
libvirt_1 | 2016-09-30 13:07:55.480+0000: 1676: info : hostname: 52a22d89ffc8
libvirt_1 | 2016-09-30 13:07:55.480+0000: 1676: warning : virLogParseOutputs:1206 : Ignoring invalid log output setting.
libvirt_1 | libvirt: Storage Driver error : Storage pool not found: no storage pool with matching name 'default'
libvirt_1 | Cleaning up VMs
libvirt_1 | All VMs cleaned
libvirt_1 | Traceback (most recent call last):
libvirt_1 | File "/cleanup.py", line 77, in 
libvirt_1 | main()
libvirt_1 | File "/cleanup.py", line 60, in main
libvirt_1 | pool = conn.storagePoolLookupByName("default")
libvirt_1 | File "/usr/lib/python2.7/dist-packages/libvirt.py", line 4575, in storagePoolLookupByName
libvirt_1 | if ret is None:raise libvirtError('virStoragePoolLookupByName() failed', conn=self)
libvirt_1 | libvirt.libvirtError: Storage pool not found: no storage pool with matching name 'default'

**Comment by YevhenD** [comment]
quick workaround change cleanup.py
try:
       pool = conn.storagePoolLookupByName("default")
       volumes = pool.listAllVolumes()
except libvirt.libvirtError:
       print("Failed fault lookup")
       volumes = set()

docker-compose build && docker-compose up

**Comment by jellonek** [comment]
There is another bug, because of which `cleanup.py` is spawning even if there is no env variable set to spawn it. Look at https://github.com/Mirantis/virtlet/blob/6e942a8756406b26a5621dea77048e54958dea16/contrib/docker/libvirt/start.sh#L17
This should be replaced with something like `[ -z "$LIBVIRT_CLEANUP" ]`, so patching this in `cleanup.py` is imo incorrect.
