### ISSUE TITLE
Instructions to deploying Windows images

### ISSUE THREAD

**Issue by kshafiee** [Mirantis/virtlet#525]
It would be great if the demo instructions can be updated to also cover the case of Windows qcow2 images
@pigmej @jellonek

**Comment by pigmej** [comment]
@kshafiee hey, basically all you need is windows qcow2 that supports dhcp. The problem that you may encounter is snapshot of volume which may take too long for kubelet, and therefore it will be restarted. We have plans to improve virtlet support for big qcow2 images soon. For now we suceeded with https://cloudbase.it/windows-cloud-images/ (you need to connect to VNC console first, because virtlet doesn't support configdrive YET, therefore their cloudinit is not fully functional, so you need to set Administrator pw via VNC console, then you can use RDP without any problems)

Does it answer your question?

**Comment by jellonek** [comment]
Actually there is nothing special needed for windows images. You can use qcow2 image from https://cloudbase.it/windows-cloud-images/ and in pod yaml description use `configdrive` as a `VirtletCloudInitImageType ` (cloudbase init supports only config drive, it does not have a support for NoCloud image types).
After that - vm just simply will boot using any configured cni.
To have a possibility to log in into this vm - you need to setup password, either by VNC, or by cloud init user data script. E.g.:
```
    VirtletCloudInitUserDataScript: |
      #ps1_sysnative
      net user Admin P@ssw0rd
      net user Administrator P@ssw0rd
```

If you still think that this should be described in https://github.com/Mirantis/virtlet/tree/master/docs or in https://github.com/Mirantis/virtlet/tree/master/deploy/ - please reopen this issue.
