### ISSUE TITLE
Support for CNI-Genie or Multus CNI Plugins

### ISSUE THREAD

**Issue by sheetaljoshi** [Mirantis/virtlet#627]
Do we support CNI-Genie or Multus CNI plugins today?

**Comment by lukaszo** [comment]
Yes we do, in few days I will create step by step guide for it.

**Comment by sheetaljoshi** [comment]
And I assume that means support of multiple interfaces and multiple ip's?

**Comment by pigmej** [comment]
@sheetaljoshi yes it does, we do have support for CNI-Genie, but you need patched / improved version from http://github.com/mirantis/CNI-Genie because not all patches landed in upstream yet. 

In theory you're allowed to use any CNI plugins, but we checked calico, flannel, sriov, contrail.

I'm pretty sure that @lukaszo can provide more details if you need them all, or just wait for docs that are landing soon.

**Comment by sheetaljoshi** [comment]
@pigmej @lukaszo I am trying to run with CNI Genie, with canal and weave-weave but virtlet-ds is stuck at PoDInitializing with master libvirt-ds.yaml and at Init stage with wget https://github.com/Mirantis/virtlet/releases/download/v0.9.4/virtlet-ds.yaml. Any change if we have documents published yet?

**Comment by sheetaljoshi** [comment]
@pigmej @lukaszo It would be great if you can share updates on this request? Please share if you have any documentation or steps that I can follow?

**Comment by lukaszo** [comment]
@sheetaljoshi I apologise for a late response. I've created document with an example describing how to use CNI-Genie with Virtlet  https://github.com/Mirantis/virtlet/blob/master/docs/multiple-interfaces.md I hope it helps

**Comment by lukaszo** [comment]
No, only CNI-Genie is supported. Multus may or may not work. We've never tried it.

**Comment by saddepalli** [comment]
Thank you.
How does virlet know about multiple interfaces and IP addresses? In our experimentation, we are using flannel as first CNI and OVN as next CNI.  OVN CNI is creating multiple interfaces by creating multiple veth pairs and adding appropriate IP addresses.  In case of docker based PODS, we see that PODS showing up all interfaces with right IP addresses - That is flannel interface and OVN interfaces are shown properly. 

When we bring up VM using virtlet, it is showing only interface related to flannel. It is not showing interfaces created by OVN.  Based on some debugging, we see that OVN CNI is getting control from Multus and we also ensured that it is indeed adding veth pairs successfully.

We thought that virtlet figures out the number of interfaces and corresponding IP addresses by looking at the interfaces in the network namespace, create as many number of tap interfaces before VM is brought up.   Please let us know how virtlet recognizes the interfaces and any other points you can think of for us to debug this further.

**Comment by jellonek** [comment]
Virtlet uses information returned from CNI plugin in form of https://github.com/containernetworking/cni/blob/master/SPEC.md#result which should contain a list of interfaces with data like ip addresses and routes to be set through them.

So probably the only information returned there (by multus?) was info about interface created/configure by flannel. This means that thing used to multiplex calls to different CNI plugins, need to be updated to fulfill CNI specification (because looks like there is some assumptions about how it's used by docksershim, while rest of it is ignored).

Maybe you should try instead of Multus CNI-Genie, which know how to properly use chain of cni plugins, collects all results and merges them before returning to CRI compliant runtime, which is calling it?

**Comment by lukaszo** [comment]
I can already see that multus is not joining the results https://github.com/intel/multus-cni/blob/master/multus/multus.go#L258

**Comment by saddepalli** [comment]
Thank you. So, it appears to be Multus issue.

**Comment by lukaszo** [comment]
It shouldn't be called by kubelet, only virtlet. Can you attach full virtlet log? From virtlet container in virtlet pod.

**Comment by jellonek** [comment]
If routes/dns settings will be visible in cni result - virtlet will pass them to vm for sure, in two ways - using cloud init network configuration passed inside of cdrom image and using dhcp server.
One note - dhcp server option is unavailable for sr-iov devices.

**Comment by saddepalli** [comment]
Okay.  Is there any configuration to select one of the options. We would like DHCP Server to provide both routes and DNS server settings along with IP address.?

**Comment by jellonek** [comment]
DHCP is serving ip/dns data always for veth based devices created by cni plugins so your requirement should be fulfilled already.

cloud init based network configuration is also always prepared (user can select a data source type - nocloud, or config drive, both are similar and based on cdrom image).

**Comment by leyao-daily** [comment]
> Yes we do, in few days I will create step by step guide for it.

The guide site is 404, could you please tell me the new address of the guide to setup sriov?

**Comment by jellonek** [comment]
PTAL on https://docs.virtlet.cloud/101/network/#multiple-interfaces

**Comment by leyao-daily** [comment]
@saddepalli Hi, By using multus cni, is the sriov device plugin and sriov cni work correctly with virtlet?

**Comment by pigmej** [comment]
We’ve checked cni-genie by ourselves. I don’t know about multus but in theory it should work fine.
